export type Candidato = {
  id: string;
  nome: string | null;
  partido: string | null;
  cargo: string | null;
  estado: string | null;
  municipio: string | null;
  dominio_formularios: string | null;
  slug_publico?: string | null;
  criado_em: string | null;
};

export type Campanha = {
  id: string;
  titulo: string | null;
  descricao: string | null;
  candidato_id: string | null;
  url_formulario: string | null;
  ativa: boolean | null;
  inicio_em: string | null;
  fim_em: string | null;
  criado_em: string | null;
  id_planilha: string | null;
  assinaturas_meta: number | null;
  texto_form: string | null;
  texto_dot: string | null;
  destaque_primario: string | null;
  destaque_secundario: string | null;
  cor_destaque: string | null;
  imagem_fundo: string | null;
  imagem_lateral: string | null;
  tema: number | null;
  texto_contexto: string | null;
  texto_proposta: string | null;
  texto_conclusao: string | null;
  texto_impacto: string | null;
  texto_impacto_apoio: string | null;
  texto_faixa: string | null;
  titulo_topicos: string | null;
  texto_topicos_intro: string | null;
  texto_topicos: string | null;
  titulo_citacao: string | null;
  texto_citacao: string | null;
  nota_citacao: string | null;
  titulo_video: string | null;
  video_url: string | null;
  texto_video: string | null;
  legenda_video: string | null;
  nota_video: string | null;
  titulo_assinar: string | null;
  texto_assinar: string | null;
  texto_compartilhar: string | null;
};

export type Assinatura = {
  id: string;
  campanha_id: string;
  nome_assinante: string | null;
  numero_assinante: string | null;
  email_assinante: string | null;
  endereco_assinante: string | null;
  n_assinante: number | null;
  complemento_assinante: string | null;
  cidade_assinante: string | null;
  cep_assinante: string | null;
  estado_assinante: string | null;
  ip_origem: string | null;
  assinado_em: string | null;
};
