-- Rewrite the published copy for every Julia de Castro campaign.
-- Campaign identifiers and slugs remain unchanged.
do $$
begin
  if not exists (
    select 1
    from public.candidatos
    where id = '44e501d2-6153-4d47-a552-8ae16be927a4'::uuid
      and nome = 'Julia de Castro'
  ) then
    raise exception 'Julia de Castro candidate record was not found';
  end if;
end
$$;

with revised_copy as (
  select *
  from jsonb_to_recordset(
    $campaigns$
    [
      {
        "id": "02b1a4ce-d68a-4322-aec5-89829a40f123",
        "titulo": "Abaixo assinado contra a censura e em defesa da liberdade de expressão",
        "descricao": "A liberdade de expressão é um direito de todos. Jornalistas, cidadãos e instituições precisam poder informar, questionar e discordar sem medo. Esta mobilização pede mais transparência, equilíbrio e respeito ao debate público.",
        "destaque_primario": "liberdade de expressão",
        "destaque_secundario": "sem censura",
        "texto_faixa": "Liberdade para informar • Direito de questionar • Respeito ao cidadão • Assine e compartilhe",
        "titulo_topicos": "Quando o silêncio avança, a sociedade perde.",
        "texto_topicos_intro": "Não é preciso concordar com todas as opiniões para defender o direito de cada pessoa se manifestar. Liberdade exige responsabilidade, mas também exige espaço para o contraditório.",
        "texto_topicos": "Informar não pode ser motivo de medo\nUma sociedade bem informada depende de jornalistas e cidadãos livres para apurar, publicar e cobrar respostas.\n\nDiscordar faz parte da democracia\nO debate público só amadurece quando posições diferentes podem ser apresentadas com respeito e sem intimidação.\n\nPoder também precisa de transparência\nToda instituição pública deve aceitar questionamentos e prestar contas de suas decisões à sociedade.\n\nA liberdade precisa de voz\nDireitos permanecem vivos quando as pessoas se posicionam. Cada assinatura mostra que o silêncio não é uma opção.",
        "titulo_citacao": "Liberdade não existe pela metade.",
        "texto_citacao": "Defender a liberdade de expressão é proteger o direito de falar, ouvir, questionar e formar a própria opinião.",
        "nota_citacao": "Esta iniciativa defende um debate público responsável, transparente e aberto à pluralidade de ideias.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Sua voz também protege a liberdade.",
        "texto_assinar": "Se você acredita que o Brasil precisa de mais transparência e liberdade para o debate público, registre seu apoio. Sua assinatura fortalece uma mensagem clara em defesa do direito de expressão.",
        "texto_compartilhar": "Eu assinei em defesa da liberdade de expressão e de um debate público sem censura. Participe também:",
        "texto_form": "Defenda a liberdade de expressão. Assine agora.",
        "texto_dot": "Liberdade de expressão",
        "meta_title": "Em defesa da liberdade de expressão",
        "meta_description": "Assine em defesa da liberdade de expressão, da transparência e do direito de questionar com responsabilidade.",
        "og_title": "Liberdade de expressão precisa de voz",
        "og_description": "Uma mobilização por transparência, pluralidade e respeito ao debate público."
      },
      {
        "id": "ed58ffdb-b358-4f0a-8a5b-119406cef2b0",
        "titulo": "Abaixo assinado por transparência e respeito às famílias na educação",
        "descricao": "Educação de qualidade se constrói com conhecimento, diálogo e confiança. As famílias precisam saber o que é apresentado em sala de aula e participar das decisões que envolvem a formação de seus filhos.",
        "destaque_primario": "famílias presentes",
        "destaque_secundario": "educação com transparência",
        "texto_faixa": "Família presente • Escola transparente • Respeito aos alunos • Assine e compartilhe",
        "titulo_topicos": "Educar também é construir confiança.",
        "texto_topicos_intro": "Escola e família não são adversárias. Quando existe transparência, todos podem trabalhar juntos por uma educação séria, acolhedora e focada no desenvolvimento dos alunos.",
        "texto_topicos": "As famílias precisam participar\nPais e responsáveis têm o direito de conhecer conteúdos, projetos e abordagens que fazem parte da rotina escolar.\n\nTemas sensíveis exigem clareza\nAssuntos que envolvem valores e formação pessoal devem ser tratados com responsabilidade, linguagem adequada e diálogo aberto.\n\nRespeito vale para todos\nNenhum aluno deve ser constrangido por sua origem, sua fé ou pelas convicções de sua família. A escola deve ser um ambiente seguro para aprender.\n\nO aprendizado vem primeiro\nLeitura, escrita, ciência, história e pensamento crítico precisam ocupar o centro da vida escolar.",
        "titulo_citacao": "Transparência aproxima escola e família.",
        "texto_citacao": "Uma educação forte respeita os alunos, valoriza os professores e reconhece a participação das famílias.",
        "nota_citacao": "Esta mobilização pede diálogo, responsabilidade e acesso claro às informações sobre a formação escolar.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Participe desta conversa.",
        "texto_assinar": "Se você defende uma educação transparente, respeitosa e aberta à participação das famílias, deixe sua assinatura. É uma forma simples de mostrar que esse diálogo importa.",
        "texto_compartilhar": "Eu assinei por transparência, respeito às famílias e uma educação focada no aprendizado. Participe também:",
        "texto_form": "Assine por uma educação transparente e respeitosa.",
        "texto_dot": "Família e educação",
        "meta_title": "Transparência e respeito às famílias na educação",
        "meta_description": "Participe da mobilização por diálogo, transparência e respeito às famílias no ambiente escolar.",
        "og_title": "Educação se faz com diálogo e transparência",
        "og_description": "Uma iniciativa pela participação das famílias e pelo respeito no ambiente escolar."
      },
      {
        "id": "f175dedd-0f35-439f-aa06-882a29e009ac",
        "titulo": "Abaixo assinado contra o Governo Lula",
        "descricao": "Quem discorda dos rumos do Governo Lula tem o direito de se posicionar. Esta mobilização reúne brasileiros que querem mais responsabilidade, prioridades claras e respeito por quem trabalha, produz e sustenta o país.",
        "destaque_primario": "o Brasil merece respostas",
        "destaque_secundario": "responsabilidade agora",
        "texto_faixa": "Mais responsabilidade • Prioridades para o Brasil • Respeito ao cidadão • Assine e compartilhe",
        "titulo_topicos": "Discordar também é participar.",
        "texto_topicos_intro": "Democracia não é silêncio. Cobrar decisões, questionar prioridades e exigir responsabilidade faz parte do papel de todo cidadão.",
        "texto_topicos": "O cidadão merece ser ouvido\nQuem sente os efeitos das decisões do governo no trabalho, na renda e na rotina precisa ter espaço para cobrar mudanças.\n\nPrioridades precisam estar no Brasil\nO país enfrenta desafios que exigem atenção, planejamento e compromisso com resultados que cheguem à vida real.\n\nDinheiro público exige responsabilidade\nCada recurso administrado pelo governo pertence à sociedade. Transparência e cuidado não são favores, são deveres.\n\nA cobrança precisa ser firme\nEsta mobilização transforma insatisfação em uma mensagem pública, legítima e clara.",
        "titulo_citacao": "Cobrar o governo é exercer cidadania.",
        "texto_citacao": "O Brasil precisa de responsabilidade, transparência e prioridades que respeitem a realidade de quem vive e trabalha no país.",
        "nota_citacao": "Este abaixo assinado expressa uma posição política de forma pacífica e democrática.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Mostre que você também quer mudança.",
        "texto_assinar": "Se você não concorda com os rumos do Governo Lula, registre sua posição. Cada assinatura reforça a cobrança por mais responsabilidade e respeito ao cidadão.",
        "texto_compartilhar": "Eu assinei por mais responsabilidade, transparência e respeito ao cidadão. Se você também quer mudança, participe:",
        "texto_form": "Registre sua posição contra os rumos do Governo Lula.",
        "texto_dot": "Responsabilidade no governo",
        "meta_title": "Abaixo assinado contra o Governo Lula",
        "meta_description": "Registre sua posição por mais responsabilidade, transparência e respeito ao cidadão brasileiro.",
        "og_title": "O Brasil merece respostas",
        "og_description": "Uma mobilização pacífica por responsabilidade, transparência e prioridades claras."
      },
      {
        "id": "7da492d8-48f1-4004-a989-6109824f09a5",
        "titulo": "Abaixo assinado em apoio a Flávio Bolsonaro",
        "descricao": "Esta mobilização reúne pessoas que veem em Flávio Bolsonaro uma voz capaz de representar quem deseja novos rumos para o Brasil. Apoio político se constrói com participação, presença e uma mensagem clara.",
        "destaque_primario": "apoio a Flávio",
        "destaque_secundario": "uma voz por mudança",
        "texto_faixa": "Participação • Coragem • Renovação • Assine e compartilhe",
        "titulo_topicos": "Apoio se demonstra com atitude.",
        "texto_topicos_intro": "Quem acredita em um projeto precisa tornar esse apoio visível. Esta campanha é um espaço para reunir pessoas, ideias e disposição para participar.",
        "texto_topicos": "Uma voz para quem quer mudança\nMuitos brasileiros procuram uma representação firme, presente e conectada às suas preocupações.\n\nParticipação fortalece escolhas\nPolítica não acontece apenas nas eleições. Ela também se constrói quando o cidadão acompanha, questiona e manifesta apoio.\n\nConvicção com responsabilidade\nApoiar alguém não significa abrir mão do senso crítico. Significa reconhecer uma direção e continuar cobrando coerência.\n\nUma mensagem que pode crescer\nCada assinatura ajuda a mostrar que existe uma base disposta a participar e defender suas escolhas de forma democrática.",
        "titulo_citacao": "Quem acredita, participa.",
        "texto_citacao": "O apoio ganha força quando deixa de ser apenas opinião e se transforma em presença.",
        "nota_citacao": "Esta é uma manifestação voluntária de apoio político e participação cidadã.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Declare seu apoio.",
        "texto_assinar": "Se você acredita que Flávio Bolsonaro pode representar os rumos que deseja para o Brasil, deixe sua assinatura. Sua participação torna esse apoio visível.",
        "texto_compartilhar": "Eu manifestei meu apoio a Flávio Bolsonaro. Se essa também é a sua escolha, participe:",
        "texto_form": "Manifeste seu apoio a Flávio Bolsonaro.",
        "texto_dot": "Apoio a Flávio",
        "meta_title": "Apoio a Flávio Bolsonaro",
        "meta_description": "Participe da mobilização e manifeste democraticamente seu apoio a Flávio Bolsonaro.",
        "og_title": "Apoio se demonstra com participação",
        "og_description": "Uma mobilização para quem deseja manifestar apoio a Flávio Bolsonaro."
      },
      {
        "id": "b30d3d7f-d508-4eb5-9d35-86c3d70ad0c1",
        "titulo": "Chega de doutrinação nas escolas",
        "descricao": "Eu quero uma educação que ensine, desperte curiosidade e prepare nossos filhos para pensar com liberdade. Sala de aula é lugar de conhecimento, respeito e diálogo.",
        "destaque_primario": "educação com liberdade",
        "destaque_secundario": "conhecimento em primeiro lugar",
        "texto_faixa": "Escola é lugar de aprender • Respeito a quem pensa diferente • Família presente • Assine e compartilhe",
        "titulo_topicos": "Eu não aceito o silêncio dentro da sala de aula.",
        "texto_topicos_intro": "Educar é ampliar horizontes. Eu defendo uma escola que apresente conhecimento, incentive perguntas e respeite alunos que chegam a conclusões diferentes.",
        "texto_topicos": "Aluno precisa aprender a pensar\nCrianças e jovens merecem acesso ao conhecimento e a pontos de vista diferentes. A escola deve formar autonomia, não repetir palavras de ordem.\n\nProfessor merece respeito\nProfessor é peça chave na educação e precisa de condições para ensinar com liberdade e responsabilidade. Aula não pode virar comício.\n\nFamília tem direito de acompanhar\nPais e responsáveis precisam conhecer o que é apresentado aos seus filhos. Acompanhamento não é perseguição. É cuidado e transparência.\n\nUniversidade também precisa de pluralidade\nQuem pensa diferente deve poder falar, estudar e debater sem intimidação. Ideias se enfrentam com argumentos.",
        "titulo_citacao": "Conhecimento abre caminhos. Doutrinação fecha.",
        "texto_citacao": "Eu defendo escola e universidade com liberdade para ensinar, aprender, perguntar e discordar.",
        "nota_citacao": "Esta mobilização reúne pessoas que querem uma educação séria, plural e comprometida com o conhecimento.",
        "titulo_video": "O relato de quem sentiu a intolerância de perto.",
        "texto_video": "Julia de Castro conta o que viveu depois de expor publicamente suas opiniões políticas enquanto estudava em uma universidade federal.\n\nSeu depoimento mostra como o ambiente acadêmico pode se tornar hostil quando o respeito ao contraditório desaparece.\n\nO relato reforça uma ideia simples: ninguém deve virar alvo por pensar diferente.",
        "legenda_video": "Relato de Julia de Castro publicado em suas redes",
        "nota_video": "O vídeo apresenta a experiência pessoal narrada por Julia de Castro.",
        "titulo_assinar": "Se você também quer liberdade para aprender, assine.",
        "texto_assinar": "Sua assinatura mostra que alunos, professores e famílias querem uma educação com conhecimento, pluralidade e respeito. Leva poucos segundos e ajuda essa mensagem a chegar mais longe.",
        "texto_compartilhar": "Eu assinei por escolas e universidades com conhecimento, pluralidade e respeito. Participe também:",
        "texto_form": "Assine por uma educação com liberdade e respeito.",
        "texto_dot": "Educação com liberdade",
        "meta_title": "Chega de doutrinação nas escolas",
        "meta_description": "Assine por escolas e universidades com conhecimento, pluralidade, transparência e respeito a quem pensa diferente.",
        "og_title": "Educação com liberdade para pensar",
        "og_description": "Uma mobilização por conhecimento, pluralidade e respeito dentro das escolas e universidades."
      },
      {
        "id": "9bbc7503-08a9-4eb6-a554-4e171a7fb369",
        "titulo": "Abaixo assinado em defesa da vida",
        "descricao": "Toda vida merece cuidado e dignidade. Esta mobilização defende acolhimento para gestantes, apoio às famílias e políticas públicas que ofereçam caminhos concretos para proteger a mãe e o bebê.",
        "destaque_primario": "em defesa da vida",
        "destaque_secundario": "acolher também é proteger",
        "texto_faixa": "Acolhimento • Proteção • Dignidade • Assine e compartilhe",
        "titulo_topicos": "Defender a vida também é oferecer apoio.",
        "texto_topicos_intro": "Uma posição responsável precisa ir além das palavras. É necessário garantir informação, cuidado e suporte para mulheres e famílias que enfrentam uma gravidez em situação difícil.",
        "texto_topicos": "Acolhimento antes do julgamento\nToda gestante merece ser ouvida e tratada com respeito, especialmente quando enfrenta medo, abandono ou dificuldade financeira.\n\nProteção para mãe e bebê\nCuidar da vida significa oferecer saúde, segurança e acompanhamento durante a gestação e depois do nascimento.\n\nFamílias precisam de suporte\nRedes de apoio, orientação e políticas públicas podem transformar momentos de insegurança em caminhos possíveis.\n\nDignidade em cada decisão pública\nLeis e políticas devem reconhecer o valor da vida e a necessidade de amparo real para quem mais precisa.",
        "titulo_citacao": "A vida precisa de proteção e acolhimento.",
        "texto_citacao": "Defender a vida é cuidar da mãe, do bebê e da família com respeito, responsabilidade e apoio concreto.",
        "nota_citacao": "Esta iniciativa propõe uma mobilização pacífica em defesa da vida e do acolhimento às gestantes.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Assine por cuidado, dignidade e vida.",
        "texto_assinar": "Se você acredita que a vida merece proteção e que nenhuma gestante deveria enfrentar uma situação difícil sem apoio, participe desta mobilização.",
        "texto_compartilhar": "Eu assinei em defesa da vida, do acolhimento às gestantes e do apoio às famílias. Participe também:",
        "texto_form": "Assine em defesa da vida e do acolhimento.",
        "texto_dot": "Cuidado e dignidade",
        "meta_title": "Abaixo assinado em defesa da vida",
        "meta_description": "Participe da mobilização por proteção à vida, acolhimento às gestantes e apoio às famílias.",
        "og_title": "Defender a vida também é acolher",
        "og_description": "Uma mobilização por cuidado, dignidade e apoio concreto para gestantes e famílias."
      },
      {
        "id": "def2a5d2-7c0d-4697-8665-7b4ed1eb94f9",
        "titulo": "Pelo livre comércio e pela liberdade econômica no Rio de Janeiro",
        "descricao": "O Centro do Rio já foi referência de comércio forte, trabalho e oportunidades. Para recuperar essa energia, quem empreende precisa de regras claras, menos burocracia e liberdade para manter as portas abertas.",
        "destaque_primario": "livre comércio",
        "destaque_secundario": "um Rio de portas abertas",
        "texto_faixa": "Menos burocracia • Mais liberdade • Comércio forte • Assine e compartilhe",
        "titulo_topicos": "O Rio precisa voltar a abrir as portas.",
        "texto_topicos_intro": "Cada loja aberta movimenta uma rua, gera trabalho e devolve vida ao bairro. Facilitar a rotina de quem empreende é uma escolha prática pelo desenvolvimento da cidade.",
        "texto_topicos": "Empreender precisa ser possível\nQuem abre ou mantém um negócio precisa de segurança, regras compreensíveis e liberdade para trabalhar.\n\nBurocracia custa tempo e oportunidade\nExigências desnecessárias afastam investimentos e consomem recursos que poderiam gerar empregos e melhorar serviços.\n\nComércio forte transforma bairros\nPortas abertas significam movimento, renda, ocupação dos espaços e mais oportunidades para quem vive no Rio.\n\nO Centro pode recuperar sua força\nRevitalização acontece quando existe gente trabalhando, investindo e acreditando novamente na cidade.",
        "titulo_citacao": "Uma cidade viva começa com portas abertas.",
        "texto_citacao": "Menos burocracia, mais liberdade econômica e respeito por quem trabalha para fazer o Rio crescer.",
        "nota_citacao": "Esta mobilização defende um ambiente mais simples, seguro e favorável para quem empreende no Rio de Janeiro.",
        "titulo_video": null,
        "texto_video": null,
        "legenda_video": null,
        "nota_video": null,
        "titulo_assinar": "Assine por um Rio que valoriza quem empreende.",
        "texto_assinar": "Se você acredita em menos burocracia, comércio forte e mais liberdade para trabalhar, registre seu apoio. Cada assinatura ajuda essa proposta a ganhar espaço.",
        "texto_compartilhar": "Eu assinei por menos burocracia, mais liberdade econômica e um Rio de portas abertas. Participe também:",
        "texto_form": "Assine por menos burocracia e mais liberdade para empreender.",
        "texto_dot": "Rio de portas abertas",
        "meta_title": "Livre comércio e liberdade econômica no Rio",
        "meta_description": "Assine por menos burocracia, comércio forte e mais liberdade para quem trabalha e empreende no Rio de Janeiro.",
        "og_title": "Um Rio de portas abertas",
        "og_description": "Menos burocracia, mais liberdade econômica e comércio forte para devolver movimento à cidade."
      }
    ]
    $campaigns$::jsonb
  ) as copy(
    id uuid,
    titulo text,
    descricao text,
    destaque_primario text,
    destaque_secundario text,
    texto_faixa text,
    titulo_topicos text,
    texto_topicos_intro text,
    texto_topicos text,
    titulo_citacao text,
    texto_citacao text,
    nota_citacao text,
    titulo_video text,
    texto_video text,
    legenda_video text,
    nota_video text,
    titulo_assinar text,
    texto_assinar text,
    texto_compartilhar text,
    texto_form text,
    texto_dot text,
    meta_title text,
    meta_description text,
    og_title text,
    og_description text
  )
)
update public.campanhas as campaign
set
  titulo = copy.titulo,
  descricao = copy.descricao,
  destaque_primario = copy.destaque_primario,
  destaque_secundario = copy.destaque_secundario,
  texto_faixa = copy.texto_faixa,
  titulo_topicos = copy.titulo_topicos,
  texto_topicos_intro = copy.texto_topicos_intro,
  texto_topicos = copy.texto_topicos,
  titulo_citacao = copy.titulo_citacao,
  texto_citacao = copy.texto_citacao,
  nota_citacao = copy.nota_citacao,
  titulo_video = copy.titulo_video,
  texto_video = copy.texto_video,
  legenda_video = copy.legenda_video,
  nota_video = copy.nota_video,
  titulo_assinar = copy.titulo_assinar,
  texto_assinar = copy.texto_assinar,
  texto_compartilhar = copy.texto_compartilhar,
  texto_form = copy.texto_form,
  texto_dot = copy.texto_dot,
  meta_title = copy.meta_title,
  meta_description = copy.meta_description,
  og_title = copy.og_title,
  og_description = copy.og_description,
  updated_at = now()
from revised_copy as copy
where campaign.id = copy.id
  and campaign.candidato_id = '44e501d2-6153-4d47-a552-8ae16be927a4'::uuid;
