-- Rewrite every campaign outside Julia de Castro's already reviewed portfolio.
-- IDs, slugs, owners, publication status and media remain unchanged.
do $$
begin
  if (select count(*) from public.campanhas where id in (
    'f0ea8937-8a12-430a-9077-c95fafcfca44','3a101f6a-4c5b-431a-933a-6ae74bd3d93c',
    'b6b55fcb-8e46-4ddc-906c-f007c8fccb92','b50dbca2-e264-4372-a6b2-9d2103f306bd',
    '4293222b-8f86-4922-b213-9a235534216f','549d96b2-c02b-48bf-8006-937b19393361',
    'ea0ebe53-e8e1-4ded-b25f-571a471948b7','cc716fc3-aab3-4aec-bbfd-817ecc3e60b0',
    '511ff6ff-c8db-444e-a4bd-2fed665cf427','e6d9a024-6d7d-42f1-95ac-45647ebfa661',
    'e0649211-c371-420d-9268-c4c1c4171a91','2bd3f341-b9cf-410a-9a71-94ce6c897a43',
    '17ee29ca-a067-4b14-a883-7aae9aa565ae','7b613ad1-66b6-46cc-ac1e-84bcc9acda31',
    'de9941ca-7110-4b16-a50d-ce63fc58ee57','91898bdb-90e9-44bf-9e8c-aefb5b559b18',
    'aa6132d5-574d-465b-8c0a-2297c66c47c4','82885db4-7033-453a-97f1-e0921ec3072f',
    'd96b0291-fa30-4776-8168-61d998a145b2','3464a2d1-28d7-4b78-8632-a6b5873e729d'
  )) <> 20 then raise exception 'Expected 20 campaigns before copy migration'; end if;
end $$;

with copy as (
  select * from jsonb_to_recordset($campaigns$[
    {"id":"f0ea8937-8a12-430a-9077-c95fafcfca44","tema":3,"theme_key":"manifesto","titulo":"Mais liberdade para as famílias escolherem a educação dos filhos","descricao":"Famílias que desejam uma formação escolar orientada por valores cristãos também querem ser ouvidas. Esta mobilização pede que São Paulo discuta, com transparência e respeito à lei, opções educacionais que atendam essa escolha.","primario":"educação com valores","secundario":"liberdade de escolha","contexto":"A educação participa da formação intelectual, ética e social de cada criança. Muitas famílias querem uma proposta pedagógica compatível com seus valores, sem abrir mão da qualidade.","acao":"Liberdade para escolher\nFamílias devem poder conhecer diferentes propostas pedagógicas.\n\nQualidade em primeiro lugar\nToda escola precisa manter compromisso com aprendizagem e segurança.\n\nDiálogo responsável\nA proposta deve respeitar a legislação e a diversidade da sociedade.","fecho":"Dar voz às famílias é abrir espaço para decisões educacionais mais conscientes."},
    {"id":"3a101f6a-4c5b-431a-933a-6ae74bd3d93c","tema":4,"theme_key":"impact-dark","titulo":"Uma base permanente da GCM para proteger o nosso bairro","descricao":"Moradores e comerciantes precisam circular com mais tranquilidade. A proposta é cobrar da Prefeitura uma base permanente da Guarda Civil Metropolitana nos pontos mais vulneráveis da região.","primario":"segurança perto de casa","secundario":"presença que protege","contexto":"Quem vive a rotina do bairro sabe o peso da insegurança.","acao":"Relatos de assaltos mudam hábitos, afastam clientes e fazem famílias evitarem ruas e horários que antes faziam parte da rotina.\n\nUma base permanente pode aproximar a segurança da população e melhorar a resposta às ocorrências.\n\nA comunidade pede planejamento, presença contínua e diálogo.","fecho":"Segurança não pode aparecer só depois do crime."},
    {"id":"b6b55fcb-8e46-4ddc-906c-f007c8fccb92","tema":2,"theme_key":"editorial","titulo":"Punição mais rigorosa para crimes sexuais contra crianças","descricao":"Crimes sexuais contra crianças exigem prevenção, acolhimento às vítimas e uma resposta firme do Estado. Esta campanha defende o debate responsável sobre medidas legais que reduzam a reincidência de condenados.","primario":"proteção às crianças","secundario":"rigor contra a reincidência","contexto":"A violência sexual deixa marcas profundas nas vítimas e em suas famílias. O enfrentamento precisa combinar investigação séria, julgamento justo, cumprimento da pena e acompanhamento especializado.","acao":"Defendemos que o Congresso debata medidas mais rigorosas para condenados por crimes sexuais contra crianças, inclusive tratamentos destinados a reduzir a reincidência quando houver respaldo jurídico, médico e científico.","fecho":"A prioridade é impedir novas vítimas sem abandonar o devido processo legal e a avaliação técnica."},
    {"id":"b50dbca2-e264-4372-a6b2-9d2103f306bd","tema":3,"theme_key":"manifesto","titulo":"Mais escolas cívico-militares para as famílias do Rio Grande do Sul","descricao":"Famílias gaúchas que acreditam em disciplina, organização e respeito querem acesso ao modelo cívico-militar. A proposta é ampliar a oferta e preservar a liberdade de escolha.","primario":"disciplina para aprender","secundario":"escolha para as famílias","contexto":"Toda família quer uma escola segura, organizada e comprometida com o aprendizado. Para muitos responsáveis, o modelo cívico-militar é uma opção que merece estar disponível.","acao":"Ordem para ensinar e aprender\nUm ambiente organizado ajuda professores e alunos.\n\nRespeito dentro da escola\nConvivência e responsabilidade fazem parte da formação.\n\nEscolha consciente\nA adesão deve ser transparente e respeitar cada comunidade.","fecho":"A família precisa ter voz na educação."},
    {"id":"4293222b-8f86-4922-b213-9a235534216f","tema":3,"theme_key":"manifesto","titulo":"Equilíbrio entre os Poderes e respeito à Constituição","descricao":"A democracia depende de instituições fortes, limites claros e respeito às competências de cada Poder. Esta mobilização defende transparência, equilíbrio e segurança jurídica.","primario":"equilíbrio entre os Poderes","secundario":"Constituição respeitada","contexto":"Executivo, Legislativo e Judiciário têm responsabilidades próprias. A sociedade precisa de regras claras, decisões fundamentadas e fiscalização permanente.","acao":"Competências claras\nCada instituição deve atuar dentro de suas atribuições.\n\nDecisões transparentes\nA sociedade precisa compreender os fundamentos das decisões públicas.\n\nFreios e contrapesos\nO equilíbrio institucional protege a democracia.","fecho":"Instituições fortes respeitam limites."},
    {"id":"549d96b2-c02b-48bf-8006-937b19393361","tema":4,"theme_key":"impact-dark","titulo":"Liberdade de expressão não pode depender de quem está falando","descricao":"A retirada de uma publicação política reacendeu uma pergunta necessária: como proteger a liberdade de expressão e, ao mesmo tempo, garantir responsabilidade e devido processo?","primario":"liberdade para todos","secundario":"o debate não pode ser apagado","contexto":"Tentaram tirar minha voz do ar. Eu escolhi responder com mais participação.","acao":"Uma decisão determinou a retirada de um vídeo meu. O episódio coloca em debate os limites de decisões que restringem manifestações públicas.\n\nCrítica, contestação e divergência fazem parte da democracia. Restrições precisam ser excepcionais e fundamentadas.\n\nEste abaixo assinado reúne quem acredita que a liberdade deve valer inclusive para quem pensa diferente.","fecho":"Hoje uma voz. Amanhã pode ser a sua."},
    {"id":"ea0ebe53-e8e1-4ded-b25f-571a471948b7","tema":2,"theme_key":"editorial","titulo":"Em defesa da propriedade e de soluções legais para conflitos de terra","descricao":"Quem trabalha, mora ou produz em uma propriedade precisa ter segurança jurídica. Conflitos de terra devem ser resolvidos pela lei, com proteção ao patrimônio e respostas sociais responsáveis.","primario":"propriedade protegida","secundario":"conflitos resolvidos pela lei","contexto":"Invasões geram insegurança para famílias e produtores e não resolvem os problemas de acesso à terra. Quando a regra é substituída pela força, toda a sociedade perde previsibilidade.","acao":"A campanha pede resposta rápida diante de invasões, cumprimento das decisões judiciais e políticas públicas que tratem conflitos fundiários pelos canais legais.","fecho":"É possível defender o patrimônio e cobrar soluções sociais sem aceitar invasões como método."},
    {"id":"cc716fc3-aab3-4aec-bbfd-817ecc3e60b0","tema":3,"theme_key":"manifesto","titulo":"Santo André precisa ouvir as famílias","descricao":"Projetos e ações públicas que afetam crianças e famílias precisam de transparência, diálogo e participação social. Esta mobilização pede que a Prefeitura escute a população antes de decidir.","primario":"famílias precisam ser ouvidas","secundario":"transparência em Santo André","contexto":"Políticas municipais alcançam a rotina das famílias, escolas e comunidades. Decisões sensíveis não devem avançar sem informação clara e participação.","acao":"Transparência desde o início\nProjetos e financiamentos precisam ser apresentados de forma acessível.\n\nEscuta das famílias\nPais e moradores devem ter canais efetivos para participar.\n\nRespeito à diversidade\nO diálogo deve acolher posições diferentes sem rótulos.","fecho":"Nada sobre as famílias sem ouvir as famílias."},
    {"id":"511ff6ff-c8db-444e-a4bd-2fed665cf427","tema":4,"theme_key":"impact-dark","titulo":"Santo André precisa enfrentar a cobrança irregular nas ruas","descricao":"Motoristas e comerciantes relatam cobranças abusivas e intimidação em espaços públicos. A cidade precisa de fiscalização contínua, canais de denúncia e proteção para quem usa as ruas.","primario":"rua pública não tem dono","secundario":"fiscalização em Santo André","contexto":"Estacionar em uma rua pública não pode virar motivo de medo ou constrangimento.","acao":"A atuação irregular de guardadores afeta moradores, clientes e comerciantes. Quando há cobrança forçada, o espaço público deixa de ser livre.\n\nA campanha pede operações regulares, orientação, canais de denúncia e resposta rápida.\n\nO objetivo é recuperar a tranquilidade e distinguir trabalho autorizado de prática abusiva.","fecho":"Espaço público deve ser seguro para todos."},
    {"id":"e6d9a024-6d7d-42f1-95ac-45647ebfa661","tema":2,"theme_key":"editorial","titulo":"Regularidade acadêmica e responsabilidade nas universidades públicas","descricao":"A sociedade financia as universidades públicas e espera ensino, pesquisa e serviços com continuidade. Esta campanha propõe discutir regras para paralisações e políticas responsáveis de prevenção às drogas.","primario":"universidade funcionando","secundario":"responsabilidade com o dinheiro público","contexto":"Interrupções prolongadas prejudicam calendários, pesquisas e estudantes. Ao mesmo tempo, políticas sobre drogas exigem critérios técnicos, respeito a direitos e acesso a cuidado.","acao":"A proposta é debater serviços acadêmicos mínimos durante paralisações e programas de prevenção, avaliação e tratamento, com regras claras e proteção à privacidade.","fecho":"Medidas sérias equilibram continuidade do ensino, direitos trabalhistas, saúde e responsabilidade."},
    {"id":"e0649211-c371-420d-9268-c4c1c4171a91","tema":2,"theme_key":"editorial","titulo":"Responsabilização proporcional para crimes graves cometidos por adolescentes","descricao":"Crimes graves exigem resposta firme, mas uma mudança na maioridade penal precisa considerar proporcionalidade, prevenção e recuperação. Esta campanha pede que o tema seja enfrentado sem slogans fáceis.","primario":"responsabilidade pelos atos","secundario":"justiça com proporcionalidade","contexto":"A violência provoca perdas reais e cobra respostas das instituições. Decisões sobre adolescentes também precisam considerar prevenção, reincidência e capacidade de recuperação.","acao":"Defendemos regras mais rigorosas para crimes graves, com critérios objetivos, análise individual, proteção às vítimas e políticas que enfrentem o recrutamento de jovens pelo crime.","fecho":"A sociedade precisa de segurança e de uma política que reduza a violência de verdade."},
    {"id":"2bd3f341-b9cf-410a-9a71-94ce6c897a43","tema":1,"theme_key":"cover","titulo":"Mais postos policiais perto de quem precisa","descricao":"Segurança se faz com presença. Levar postos policiais a mais bairros aproxima o atendimento, melhora a resposta às ocorrências e devolve tranquilidade a famílias, trabalhadores e comerciantes.","primario":"segurança mais perto","secundario":"mais postos nos bairros","contexto":"","acao":"","fecho":"Assine por uma segurança mais próxima da população."},
    {"id":"17ee29ca-a067-4b14-a883-7aae9aa565ae","tema":2,"theme_key":"editorial","titulo":"Português claro e participação das famílias na escola","descricao":"A escola deve ensinar a norma da língua portuguesa com clareza e manter diálogo aberto com as famílias. Esta campanha pede transparência sobre práticas pedagógicas e respeito a todos os alunos.","primario":"clareza na sala de aula","secundario":"famílias presentes","contexto":"Mudanças de linguagem geram dúvidas entre pais, professores e estudantes. O caminho é apresentar critérios pedagógicos, ouvir as famílias e garantir um ambiente sem constrangimento.","acao":"A campanha defende a norma da língua portuguesa nas atividades formais e pede que abordagens complementares sejam informadas, contextualizadas e discutidas com a comunidade escolar.","fecho":"A sala de aula precisa aproximar, não dividir."},
    {"id":"7b613ad1-66b6-46cc-ac1e-84bcc9acda31","tema":2,"theme_key":"editorial","titulo":"Prevenção às drogas e cuidado nas universidades públicas","descricao":"A universidade pública precisa ser um ambiente seguro e preparado para prevenir o uso problemático de drogas. Qualquer política de exames deve ter base técnica, privacidade e acesso a tratamento.","primario":"prevenção com responsabilidade","secundario":"cuidado e compromisso público","contexto":"O uso problemático de drogas é uma questão de saúde e segurança que não se resolve com omissão nem com medidas indiscriminadas que ignorem direitos e evidências.","acao":"A proposta é discutir avaliações em situações justificadas, acompanhadas de prevenção, confidencialidade, contraditório e tratamento. O objetivo deve ser cuidar e reduzir riscos, não apenas punir.","fecho":"Uma política séria combina compromisso acadêmico, saúde, segurança e dignidade."},
    {"id":"de9941ca-7110-4b16-a50d-ce63fc58ee57","tema":1,"theme_key":"cover","titulo":"Menos impostos e mais respeito por quem trabalha","descricao":"O dinheiro público começa no esforço de cada cidadão. Cobrar menos, gastar melhor e mostrar com clareza onde cada recurso foi aplicado é obrigação de qualquer governo.","primario":"menos impostos","secundario":"mais respeito ao seu dinheiro","contexto":"","acao":"","fecho":"Assine por impostos mais justos, transparência e responsabilidade."},
    {"id":"91898bdb-90e9-44bf-9e8c-aefb5b559b18","tema":2,"theme_key":"editorial","titulo":"Revisão da Área Azul nas cidades do Rio Grande do Sul","descricao":"Estacionar em via pública não pode virar uma cobrança automática sem transparência. Esta campanha pede que municípios revisem custos, resultados e impacto da Área Azul no comércio local.","primario":"vaga pública com regra justa","secundario":"transparência na Área Azul","contexto":"Quando a cidade cobra pelo estacionamento rotativo, precisa demonstrar por que a medida é necessária, como o valor é definido e onde o recurso é aplicado.","acao":"A proposta é revisar contratos e resultados, ouvir moradores e comerciantes e encerrar cobranças que não comprovem benefício real para mobilidade e acesso ao comércio.","fecho":"Cobrança pública exige prestação de contas."},
    {"id":"aa6132d5-574d-465b-8c0a-2297c66c47c4","tema":4,"theme_key":"impact-dark","titulo":"Free Flow precisa de transparência, alternativa e cobrança justa","descricao":"Circular pelas estradas gaúchas não pode se transformar em cobranças confusas e multas inesperadas. O sistema precisa ser simples, auditável e justo para quem dirige.","primario":"pedágio com regra clara","secundario":"respeito ao motorista","contexto":"Cobrança automática não pode significar surpresa automática.","acao":"O Free Flow exige informação acessível, meios simples de pagamento e comunicação antes de qualquer penalidade.\n\nTarifas e contratos precisam ser transparentes. Usuários devem conhecer critérios e prazos.\n\nA mobilização pede revisão das cobranças e proteção contra multas injustas.","fecho":"Tecnologia deve facilitar a vida, não criar armadilhas."},
    {"id":"82885db4-7033-453a-97f1-e0921ec3072f","tema":3,"theme_key":"manifesto","titulo":"Praças da Bíblia como espaços de cultura, encontro e reflexão","descricao":"A proposta é criar espaços públicos bem cuidados para cultura, convivência e expressão da tradição cristã, com acesso aberto e respeito a toda a comunidade.","primario":"fé que acolhe","secundario":"espaços que aproximam","contexto":"Praças podem ser mais do que locais de passagem. Quando recebem cuidado, programação e identidade, tornam-se pontos de encontro que fortalecem vínculos.","acao":"Cultura e memória\nA tradição bíblica faz parte da história de muitas comunidades.\n\nConvivência aberta\nOs espaços devem acolher famílias e ações comunitárias sem excluir ninguém.\n\nCuidado permanente\nImplantação e manutenção precisam ter planejamento e transparência.","fecho":"Uma praça ganha sentido quando a comunidade se reconhece nela."},
    {"id":"d96b0291-fa30-4776-8168-61d998a145b2","tema":2,"theme_key":"editorial","titulo":"Prioridades antes de grandes shows pagos pelas prefeituras","descricao":"Antes de bancar grandes cachês, cada prefeitura precisa garantir serviços essenciais e explicar o retorno de qualquer evento. Esta campanha pede prioridade e responsabilidade com o dinheiro público.","primario":"dinheiro público com prioridade","secundario":"transparência antes do palco","contexto":"Eventos podem movimentar cultura e economia, mas não justificam contratos sem transparência ou gastos incompatíveis com a realidade do município.","acao":"A proposta é impedir grandes shows financiados por prefeituras quando houver serviços essenciais descobertos e exigir publicidade dos custos, critérios e resultados esperados.","fecho":"Cultura sim. Descontrole não."},
    {"id":"3464a2d1-28d7-4b78-8632-a6b5873e729d","tema":2,"theme_key":"editorial","titulo":"Carnaval com distância segura de hospitais e locais de culto","descricao":"Festa, saúde e liberdade religiosa podem conviver com planejamento. Esta campanha pede regras de distância, horário e ruído para proteger pacientes, profissionais e comunidades.","primario":"festa com responsabilidade","secundario":"respeito a quem precisa de silêncio","contexto":"Hospitais precisam de acesso livre, descanso e condições adequadas de trabalho. Locais de culto também têm direito a realizar suas atividades sem bloqueios ou ruído excessivo.","acao":"A proposta é definir critérios para trajetos, palcos, horários, volume sonoro e acesso de emergência nas proximidades desses locais, com fiscalização e diálogo prévio.","fecho":"Respeito também faz parte da festa."}
  ]$campaigns$::jsonb) as x(
    id uuid, tema integer, theme_key text, titulo text, descricao text,
    primario text, secundario text, contexto text, acao text, fecho text
  )
)
update public.campanhas c set
  tema = copy.tema,
  theme_key = copy.theme_key,
  titulo = copy.titulo,
  descricao = copy.descricao,
  destaque_primario = copy.primario,
  destaque_secundario = copy.secundario,
  texto_faixa = case when copy.tema in (3,4) then copy.primario || ' • ' || copy.secundario end,
  texto_contexto = case when copy.tema in (2,4) then copy.contexto end,
  texto_proposta = case when copy.tema = 2 then copy.acao end,
  texto_conclusao = case when copy.tema = 2 then copy.fecho end,
  titulo_topicos = case when copy.tema in (3,4) then copy.titulo end,
  texto_topicos_intro = case when copy.tema = 3 then copy.contexto end,
  texto_topicos = case when copy.tema in (3,4) then copy.acao end,
  titulo_citacao = case when copy.tema = 3 then copy.primario end,
  texto_citacao = case when copy.tema = 3 then copy.fecho end,
  nota_citacao = case when copy.tema = 3 then 'Uma proposta aberta ao debate e à participação cidadã.' end,
  texto_impacto = case when copy.tema in (2,4) then copy.primario end,
  texto_impacto_apoio = case when copy.tema in (2,4) then copy.fecho end,
  titulo_assinar = case when copy.tema in (3,4) then 'Sua voz fortalece esta causa.' end,
  texto_assinar = case when copy.tema in (3,4) then 'Leia, assine e ajude esta proposta a chegar a mais pessoas.' end,
  texto_compartilhar = case when copy.tema in (3,4) then 'Eu apoiei esta mobilização. Conheça e participe também:' end,
  texto_form = 'Assine e mostre seu apoio.',
  texto_dot = copy.primario,
  meta_title = left(copy.titulo, 120),
  meta_description = left(copy.descricao, 320),
  og_title = left(copy.titulo, 120),
  og_description = left(copy.descricao, 320),
  updated_at = timezone('utc', now())
from copy where c.id = copy.id;

do $$
begin
  if exists (
    select 1 from public.campanhas
    where (tema = 1 and theme_key <> 'cover')
       or (tema = 2 and theme_key <> 'editorial')
       or (tema = 3 and theme_key <> 'manifesto')
       or (tema = 4 and theme_key <> 'impact-dark')
  ) then raise exception 'Campaign theme invariant failed'; end if;
end $$;
